export const movies = [
  {
    adult: false,
    backdrop_path: "/p1F51Lvj3sMopG948F5HsBbl43C.jpg",
    genre_ids: [28, 12, 14],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinct...",
    popularity: 14911.5,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.7,
    vote_count: 1523,
  },
  {
    adult: false,
    backdrop_path: "/hT9ZUwLN5tB2O7miBu1oIMJFqJT.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over th...",
    popularity: 7141.725,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 7.1,
    vote_count: 2347,
  },
  {
    adult: false,
    backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
    genre_ids: [10751, 16, 12, 35, 14],
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enou...",
    popularity: 6798.941,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.5,
    vote_count: 559,
  },
  {
    adult: false,
    backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    genre_ids: [28, 18],
    id: 361743,
    original_language: "en",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advanceme...",
    popularity: 5577.324,
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    release_date: "2022-05-24",
    title: "Top Gun: Maverick",
    video: false,
    vote_average: 8.3,
    vote_count: 1768,
  },
  {
    adult: false,
    backdrop_path: "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
    genre_ids: [27, 53],
    id: 756999,
    original_language: "en",
    original_title: "The Black Phone",
    overview:
      "Finney Shaw, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a sou...",
    popularity: 4012.081,
    poster_path: "/p9ZUzCyy9wRTDuuQexkQ78R2BgF.jpg",
    release_date: "2022-06-22",
    title: "The Black Phone",
    video: false,
    vote_average: 8,
    vote_count: 1468,
  },
  {
    adult: false,
    backdrop_path: "/27Mj3rFYP3xqFy7lnz17vEd8Ms.jpg",
    genre_ids: [28, 53],
    id: 725201,
    original_language: "en",
    original_title: "The Gray Man",
    overview:
      "When a shadowy CIA agent uncovers damning agency secrets, he's hunted across the globe by a sociopat...",
    popularity: 3897.418,
    poster_path: "/8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg",
    release_date: "2022-07-13",
    title: "The Gray Man",
    video: false,
    vote_average: 7,
    vote_count: 1058,
  },
  {
    adult: false,
    backdrop_path: "/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg",
    genre_ids: [16, 878, 12, 28, 10751],
    id: 718789,
    original_language: "en",
    original_title: "Lightyear",
    overview:
      "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of amb...",
    popularity: 3497.267,
    poster_path: "/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
    release_date: "2022-06-15",
    title: "Lightyear",
    video: false,
    vote_average: 7.4,
    vote_count: 1157,
  },
  {
    adult: false,
    backdrop_path: "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
    genre_ids: [14, 28, 12],
    id: 453395,
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and da...",
    popularity: 3427.761,
    poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    release_date: "2022-05-04",
    title: "Doctor Strange in the Multiverse of Madness",
    video: false,
    vote_average: 7.5,
    vote_count: 4982,
  },
  {
    adult: false,
    backdrop_path: "/4dNv1W1KMSLdYGz0tCEaynF0E4Q.jpg",
    genre_ids: [28, 53, 80],
    id: 854467,
    original_language: "en",
    original_title: "Indemnity",
    overview:
      "An ex-fireman with PTSD goes on the run when accused of a crime he doesn't even remember committing,...",
    popularity: 2557.388,
    poster_path: "/tVbO8EAbegVtVkrl8wNhzoxS84N.jpg",
    release_date: "2022-02-11",
    title: "Indemnity",
    video: false,
    vote_average: 6.3,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: "/l99dylTOAMkwKSr54X5ytiEtnLA.jpg",
    genre_ids: [14, 12, 28],
    id: 919355,
    original_language: "en",
    original_title: "Dragon Knight",
    overview:
      "Many years after the war has been lost, and all the dragons slain, a lone knight travels the lands o...",
    popularity: 2109.303,
    poster_path: "/uSMJbYhaEpQtF9vkMhpgljc0CA4.jpg",
    release_date: "2022-03-21",
    title: "Dragon Knight",
    video: false,
    vote_average: 6.2,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/nGpSo9gDtHOM9lpFCqOD3rjbhd9.jpg",
    genre_ids: [53, 80],
    id: 728366,
    original_language: "en",
    original_title: "Borrego",
    overview:
      "A young botanist relocates to a small desert town to study an invasive plant species. While out on r...",
    popularity: 2087.858,
    poster_path: "/kPzQtr5LTheO0mBodIeAXHgthYX.jpg",
    release_date: "2022-01-14",
    title: "Borrego",
    video: false,
    vote_average: 6,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: "/5PnypKiSj2efSPqThNjTXz8jwOg.jpg",
    genre_ids: [14, 28],
    id: 759175,
    original_language: "en",
    original_title: "The Princess",
    overview:
      "A beautiful, strong-willed young royal refuses to wed the cruel sociopath to whom she is betrothed a...",
    popularity: 1971.938,
    poster_path: "/9pCoqX24a6rE981fY1O3PmhiwrB.jpg",
    release_date: "2022-06-16",
    title: "The Princess",
    video: false,
    vote_average: 7.1,
    vote_count: 339,
  },
  {
    adult: false,
    backdrop_path: "/ftGzl2GCyko61Qp161bQElN2Uzd.jpg",
    genre_ids: [28, 53],
    id: 961484,
    original_language: "en",
    original_title: "Last Seen Alive",
    overview:
      "After Will Spann's wife suddenly vanishes at a gas station, his desperate search to find her leads h...",
    popularity: 1918.335,
    poster_path: "/qvqyDj34Uivokf4qIvK4bH0m0qF.jpg",
    release_date: "2022-05-19",
    title: "Last Seen Alive",
    video: false,
    vote_average: 6.6,
    vote_count: 171,
  },
  {
    adult: false,
    backdrop_path: "/b1L7qevxiVpkVFq4dmdQPGFPWH0.jpg",
    genre_ids: [27],
    id: 836225,
    original_language: "en",
    original_title: "The Exorcism of God",
    overview:
      "An American priest working in Mexico is considered a saint by many local parishioners. However, due ...",
    popularity: 1892.922,
    poster_path: "/hangTmbxpSV4gpHG7MgSlCWSSFa.jpg",
    release_date: "2022-03-11",
    title: "The Exorcism of God",
    video: false,
    vote_average: 7.1,
    vote_count: 448,
  },
  {
    adult: false,
    backdrop_path: "/jazlkwXfw4KdF6fVTRsolOvRCmu.jpg",
    genre_ids: [53],
    id: 924482,
    original_language: "en",
    original_title: "The Ledge",
    overview:
      "A rock climbing adventure between two friends turns into a terrifying nightmare. After Kelly capture...",
    popularity: 1882.003,
    poster_path: "/mKFT6Q7PjrRLYuPLfmH4WLCXOiD.jpg",
    release_date: "2022-02-18",
    title: "The Ledge",
    video: false,
    vote_average: 6.2,
    vote_count: 73,
  },
  {
    adult: false,
    backdrop_path: "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of bein...",
    popularity: 1878.505,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.1,
    vote_count: 14438,
  },
  {
    adult: false,
    backdrop_path: "/zTffxrYeeKfDMuaIeabDjKTaSuX.jpg",
    genre_ids: [27, 53],
    id: 629015,
    original_language: "en",
    original_title: "Shut In",
    overview:
      "A young single mother is held captive along with her two children by a violent ex and must plot thei...",
    popularity: 1862.823,
    poster_path: "/b5ug4LyLQFeR6azAJyIPBQz5ur9.jpg",
    release_date: "2022-03-24",
    title: "Shut In",
    video: false,
    vote_average: 7.1,
    vote_count: 137,
  },
  {
    adult: false,
    backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
    genre_ids: [28, 12, 10751, 35],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His t...",
    popularity: 1543.118,
    poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    release_date: "2022-03-30",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.7,
    vote_count: 2659,
  },
  {
    adult: false,
    backdrop_path: "/t0mwKhUDa62hdhdKSsN4xMfhY5Z.jpg",
    genre_ids: [18, 35],
    id: 626735,
    original_language: "en",
    original_title: "Dog",
    overview:
      "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend'...",
    popularity: 1519.324,
    poster_path: "/rkpLvPDe0ZE62buUS32exdNr7zD.jpg",
    release_date: "2022-02-17",
    title: "Dog",
    video: false,
    vote_average: 7.4,
    vote_count: 725,
  },
  {
    adult: false,
    backdrop_path: "/33qGtN2GpGEb94pn25PDPeWQZLk.jpg",
    genre_ids: [28, 80, 53],
    id: 894169,
    original_language: "en",
    original_title: "Vendetta",
    overview:
      "When his daughter is murdered, William Duncan takes the law into his own hands, setting out on a que...",
    popularity: 1411.089,
    poster_path: "/7InGE2Sux0o9WGbbn0bl7nZzqEc.jpg",
    release_date: "2022-05-17",
    title: "Vendetta",
    video: false,
    vote_average: 6.5,
    vote_count: 113,
  },
];
